rango/urls.py
from unicodedata import name
from django.urls import path
from rango import views

app_name = 'rango'

urlpatterns = [
    # 就是在URL为....../rango/时，/rango被tango_with_django_project中的urls.py处理了，分发到我们rango这个app下的urls.py中
    # 然后如果rango后面什么都没有了，那么对应''，我们rango里面的映射，把它映射到views.py文件下的index方法，返回一个搞静态的页面
    path('', views.index, name = 'index'),
    path('about/', views.about, name = 'about'),
    path('category/<slug:category_name_slug>/', views.show_category, name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('category/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('restricted/', views.restricted, name='restricted'),
    path('logout/', views.user_logout, name='logout'),
    ]

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.index, name ='index'),
    # The following maps any URLs starting with rango/ to be handled by rango
    path('rango/', include('rango.urls')),
    path('admin/', admin.site.urls),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# 上面加号后面的内容是让你配置media文件用的，用来动态拿资源

rango/models.py
# models.py 模块的顶部应该有 from django.db import models。如果没有，自己动手加上。
import datetime
import imp
from statistics import mode
from unicodedata import category
import django
from django.db import models
from django.utils import timezone
# 导入 slugify() 函数
from django.template.defaultfilters import slugify
#导入User
from django.contrib.auth.models import User

# 注意 model类 都是数据库相关
# Create your models here.
# 这个model类表示 分类，它要继承django.db.models.Model，也就是括号中的内容
class Category(models.Model):
    NAME_MAX_LENGTH = 128
    # name字段是独一无二的，而且长度为128
    name = models.CharField(max_length=NAME_MAX_LENGTH, unique=True)
    # 更新 Category 模型，加上 views 和 likes 字段，二者的默认值均是零。
    # views 是查看次数，likes是点赞次数
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    
    # 注意，只要分类名称变了，别名就随之改变。
    # slug = models.SlugField()
    
    # 解决方法一，更新模型，把 slug 字段设为允许空值
    # slug = models.SlugField(blank=True)
    
    # 第二个问题也不难解决，只需把 slug 字段设为唯一的。为 slug 字段添加约束
    slug = models.SlugField(unique=True)
    
    # save方法
    # 通过迁移工具能把 slug 字段添加到数据库中，而且可以为该字段指定默认值。
    # 可是，每个分类的别名应该是不同的。因此，我们将先执行迁移，然后重新运行填充脚本。之所
    # 以这么做，是因为填充脚本会在分类上调用 save() 方法，从而触发上面实现的 save() 方法，更新各分类的别名。
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)
    
    # 特殊的复数形式
    class Meta:
        verbose_name_plural = 'Categories'
    def __str__(self):
        return self.name

# 这个分类表示 网页
class Page(models.Model):
    TITLE_MAX_LENGTH = 128
    URL_MAX_LENGTH = 200
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=TITLE_MAX_LENGTH)
    url = models.URLField()
    views = models.IntegerField(default=0)
    pub_date = models.DateTimeField('date published', default = timezone.now)
    # 判断是不是近期发布的，一天内
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    # __str__()
    def __str__(self):  
        return self.title

class UserProfile(models.Model):
    # 这一行是必须的
    # 建立与User模型之间的关系
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    # 想增加的属性
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to = 'profile_images', blank = True)
    
    # 此外，注意 ImageField 字段的 upload_to 参数。这个参数的值与项目的 MEDIA_ROOT 设置（第 4
    # 章）结合在一起，确定上传的头像存储在哪里。假如 MEDIA_ROOT 的值为
    # <workspace>/tango_with_django_project/media/，upload_to 参数的值为 profile_images，那么头
    # 像将存储在 <workspace>/tango_with_django_project/media/profile_images/ 目录中。
    
    # 覆盖 __str__() 方法，返回有意义的字符串
    # 如果使用 Python 2.7.x，还要定义 __unicode__ 方法
    def __str__(self):
        return self.user.username
    

rango/forms.py
from django import forms
from rango.models import Page, Category
from rango.models import User, UserProfile

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128,help_text="Please enter the category name.")
    # widget 小工具
    views= forms.IntegerField(widget=forms.HiddenInput(),initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(),initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(),required=False)
    # CategoryForm 中包含 slug 字段，但是没有为其指定初始值或默认值，而是隐藏了，并且指明这个
    # 字段不是必须的。这是因为模型在调用 save() 方法保存时会生成这个字段的值。
    
    # 嵌套的类，为表单提供额外信息
    class Meta:
        # 把这个 ModelForm 与一个模型连接起来
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=Page.TITLE_MAX_LENGTH,help_text="Please enter the title of the page.")
    # url = forms.URLField(max_length=200,help_text="Please enter the URL of the page.")
    url = forms.URLField(max_length=Page.URL_MAX_LENGTH,help_text="Please enter the URL of the page.")
    # widget=forms.HiddenInput()表示把这个字段藏起来
    views = forms.IntegerField(widget=forms.HiddenInput(),initial=0)
    
    
    class Meta:
        # 把这个 ModelForm 与一个模型连接起来
        model = Page
        # 排除'category'
        exclude = ('category',)
    # 想在表单中放哪些字段？
    # 有时不需要全部字段
    # 有些字段接受空值，因此可能无需显示
    # 这里我们想隐藏外键字段
    # 为此，可以排除 category 字段
    # 也可以直接指定想显示的字段（不含 category 字段），如下：
    # fields = ('title', 'url', 'views')
    
    # 重写clean()方法
    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url and not url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url'] = url
        
        return cleaned_data
        

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password')
        
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')
    
    
    
    

rango/views.py
from django.urls import reverse
from django.http import HttpResponse
from django.shortcuts import redirect, render
from rango.models import Category
# 首先导入 Page 模型，即把下述导入语句添加到文件顶部：
from rango.models import Page

# 在文件顶部添加这个导入语句
from rango.forms import CategoryForm

from rango.forms import PageForm

from rango.forms import UserForm, UserProfileForm

from django.contrib.auth import authenticate,login
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout

from datetime import datetime


# Create your views here.
def index(request):
    request.session.set_test_cookie()
    # return HttpResponse("Rango says hey there partner!")
    # Construct a dictionary to pass to the template engine as its context.
    # Note the key boldmessage matches to {{ boldmessage }} in the template!
    # 构建一个字典，传递给模板引擎作为其上下文。
    # 注意键boldmessage与模板中的{{ boldmessage }}相匹配!
    # context_dict = {'boldmessage': 'Crunchy, creamy, cookie, candy, cupcake!'}
    bold_message = 'Crunchy, creamy, cookie, candy, cupcake!'
    
    # 查询数据库，获取目前存储的所有分类
    # 按点赞次数倒序排列分类
    # 获取前 5 个分类（如果分类数少于 5 个，那就获取全部）
    # 把分类列表放入 context_dict 字典
    # 稍后传给模板引擎
    category_list =Category.objects.order_by('-likes')[:5]
    
    # 拿到浏览量前五的网站，倒序（由大到小）
    page_list = Page.objects.order_by('-views')[:5]    
    context_dict = {'categories': category_list, 'boldmessage': bold_message, 'pages': page_list}
        
    # 调用处理 cookie 的辅助函数
    visitor_cookie_handler(request)
    
    
    # 提前获取 response 对象，以便添加 cookie
    response = render(request, 'rango/index.html', context=context_dict)
    
    # 返回 response 对象，更新目标 cookie
    return response
    
    
    # Return a rendered response to send to the client.
    # We make use of the shortcut function to make our lives easier.
    # Note that the first parameter is the template we wish to use.
    # 返回一个渲染好的响应，发送给客户端。
    # 我们利用快捷键函数来使我们的生活更轻松。
    # 注意，第一个参数是我们希望使用的模板。
    # return render(request, 'rango/index.html', context=context_dict)

def about(request):
    if request.session.test_cookie_worked():
        context_dict = {}
        context_dict['boldmessage'] = 'This tutorial has been put together by Xinhao'
        print("TEST COOKIE WORKED!")
        request.session.delete_test_cookie()
    # return HttpResponse("Rango says here is the about page!")
    # return render(request, 'rango/about.html')
    # 打印请求方法，是 GET 还是 POST
    print(request.method)
    # 打印用户名，如未登录，打印“AnonymousUser”
    print(request.user)

    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
    response = render(request,'rango/about.html',context=context_dict)
    return response
# 注意，render() 函数的最后一个参数是上下文字典，用于把额外的数据传给 Django 模板引擎。因为这里没什么额外数据要传给模板，所以使用一个空字典。







# 然后定义视图 show_category()
def show_category(request, category_name_slug):
    # 创建上下文字典，稍后传给模板渲染引擎
    context_dict = {}
    
    try:
        # 能通过传入的分类别名找到对应的分类吗？
        # 如果找不到，.get() 方法抛出 DoesNotExist 异常
        # 因此 .get() 方法返回一个模型实例或抛出异常
        category = Category.objects.get(slug=category_name_slug)
        
        # 检索关联的所有网页
        # 注意，filter() 返回一个网页对象列表或空列表
        pages = Page.objects.filter(category=category)
        
        # 把得到的列表赋值给模板上下文中名为 pages 的键
        context_dict['pages'] = pages
        # 也把从数据库中获取的 category 对象添加到上下文字典中
        # 我们将在模板中通过这个变量确认分类是否存在
        context_dict['category'] = category
        
    except Category.DoesNotExist:
        # 没找到指定的分类时执行这里
        # 什么也不做
        # 模板会显示消息，指明分类不存在
        context_dict['category'] = None
        context_dict['pages'] = None
    #debug: 我这里之前缩进去了    
    # 渲染响应，返回给客户端
    return render(request, 'rango/category.html', context_dict)
        
'''
这个视图的基本步骤与 index() 视图一样。首先定义上下文字典,然后尝试从模型中提取数据,
并把相关数据添加到上下文字典中。我们通过传给 show_category() 视图函数的
category_name_slug 参数确认要查看的是哪个分类。如果通过别名找到了分类,获取与之关联的
网页,并将其添加到上下文字典 context_dict 中。
'''
@login_required
def add_category(request):
    form = CategoryForm()
    
    # 是 HTTP POST 请求吗？
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        
        # 表单数据有效吗？
        if form.is_valid():
            
            # 把新分类存入数据库
            '''
            确认分类成功添加的另一种方法是修改 rango/views.py 文件中的 add_category() 函数,把
            form.save(commit=True) 改成 cat = form.save(commit=True),为通过表单创建的分类对象
            提供一个引用,这样便可以在控制台中打印分类,例如 print(cat, cat.slug)。
            '''
            cat = form.save(commit=True)
            
            # 保存新分类后可以显示一个确认消息
            # 不过既然最受欢迎的分类在首页
            # 那就把用户带到首页吧
            # return index(request)
        
            # 用重定向
            return redirect('/rango/')
        else:
            
            # 表单数据有错误
            # 直接在终端里打印出来
            print(form.errors)
            
    # 处理有效数据和无效数据之后
    # 渲染表单，并显示可能出现的错误消息
    return render(request,'rango/add_category.html',{'form': form})

@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None
        
    # You cannot add a page to a Category that does not exist...
    if category is None:
        return redirect('/rango/')    
    
    form = PageForm()
    # 是HTTP POST 请求吗？
    if request.method == 'POST':
        form = PageForm(request.POST)
        
        # 表单数据有效吗？
        if form.is_valid():
            if category:
                # 先拿到form对象
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                # form.save(commit=True)
                page.save()
                # probably better to use a redirect here.
                # 虽然这种写法比较好, 但无法通过测试
                # return show_category(request, category_name_slug)
            
                # 用重定向
                return redirect(reverse('rango:show_category',kwargs={'category_name_slug':category_name_slug}))
        else:
            print(form.errors)

    context_dict = {'form':form, 'category': category}
    
    
    # 处理有效数据和无效数据之后
    # 渲染表单，并显示可能出现的错误消息
    return render(request, 'rango/add_page.html', context_dict)



def register(request):
    # 一个布尔值，告诉模板注册是否成功
    # 一开始设为 False，注册成功后改为 True
    registered = False
    # 如果是 HTTP POST 请求，处理表单数据
    if request.method == 'POST':
        # 尝试获取原始表单数据
        # 注意，UserForm 和 UserProfileForm 中的数据都需要
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)
        # 如果两个表单中的数据是有效的……
        if user_form.is_valid() and profile_form.is_valid():
            # 把 UserForm 中的数据存入数据库
            user = user_form.save()
            # 使用 set_password 方法计算密码哈希值
            # 然后更新 user 对象
            user.set_password(user.password)
            user.save()
            
            # 现在处理 UserProfile 实例
            # 因为要自行处理 user 属性，所以设定 commit=False
            # 延迟保存模型，以防出现完整性问题
            profile = profile_form.save(commit=False)
            profile.user = user

            # 用户提供头像了吗？
            # 如果提供了，从表单数据库中提取出来，赋给 UserProfile 模型
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            # 保存 UserProfile 模型实例
            profile.save()
            # 更新变量的值，告诉模板成功注册了
            registered = True
        else:
            # 表单数据无效，出错了？
            # 在终端打印问题
            print(user_form.errors,profile_form.errors)
    else:
        # 不是 HTTP POST 请求，渲染两个 ModelForm 实例
        # 表单为空，待用户填写
        user_form = UserForm()
        profile_form = UserProfileForm()
    
    return render(request,
                  'rango/register.html',
                  {'user_form':user_form,
                   'profile_form':profile_form,
                   'registered':registered})

def user_login(request):
    if request.method == 'POST':
        # 获取用户在登录表单中输入的用户名和密码
        # 我们使用的是 request.POST.get('<variable>')
        # 而不是 request.POST['<variable>']
        # 这是因为对应的值不存在时，前者返回 None，
        # 而后者抛出 KeyError 异常
        username = request.POST.get('username')
        password = request.POST.get('password')

        # 使用 Django 提供的函数检查 username/password 是否有效
        # 如果有效，返回一个 User 对象
        user = authenticate(username=username,password=password)

        # 如果得到了 User 对象，说明用户输入的凭据是对的
        # 如果是 None（Python 表示没有值的方式），说明没找到与凭据匹配的用户
        if user:
            # 账户激活了吗？可能被禁了
            if user.is_active:
                # 登入有效且已激活的账户
                # 然后重定向到首页
                login(request,user)
                return redirect(reverse('rango:index'))
            else:
                return HttpResponse("Your Rango account is disabled.")
        else:
            print(f"Invalid login details: {username} , {password}")
            return HttpResponse("Invalid login details supplied.")

    # 不是 HTTP POST 请求，显示登录表单
    # 极有可能是 HTTP GET 请求
    else:
        # 没什么上下文变量要传给模板系统
        # 因此传入一个空字典
        return render(request,'rango/login.html')
    
    
@login_required
def restricted(request):
    return render(request,'rango/restricted.html')

@login_required
def user_logout(request):
    logout(request)
    # 重定向到首页
    return redirect(reverse('rango:index'))

def visitor_cookie_handler(request):
    # 获取网站的访问次数
    # 使用 COOKIES.get() 函数读取“visits”cookie
    # 如果目标 cookie 存在，把值转换为整数
    # 如果目标 cookie 不存在，返回默认值 1
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request,'last_visit',str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7],'%Y-%m-%d %H:%M:%S')
    
    # 如果距上次访问已超过一天……
    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        
        # 增加访问次数后更新“last_visit”cookie
        request.session['last_visit'] = str(datetime.now())
    else:
        # 设定“last_visit”cookie
        request.session['last_visit'] = last_visit_cookie

templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    About Rango
{% endblock %}

{% block body_block %}
    <h1>
        Rango says...
    </h1>
    <div>
        here is the about page. <br />
        <strong>This tutorial has been put together by Xinhao</strong>
    </div>
    <p>Visits: {{ visits }}</p>
    <div>
        <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
    </div>
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add a Category
{% endblock %}

{% block body_block %}
    <h1>Add a Category</h1>
    <div>
        <!-- <form id="category_form" method="post" action="/rango/add_category/"> -->
            <form id="category_form" method="post" action="{% url 'rango:add_category' %}"></form>
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
            <input type="submit" name="submit" value="Create Category"/>
        </form>
    </div>>
{% endblock %}

templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
    
{% block title_block %}
    Add a Page
{% endblock %}


{% block body_block %}
        {% if category %}
        
        <h1>Add a Page to {{category.name}}</h1>

        <form id="page_form" method="post" action="/rango/category/{{ category.slug }}/add_page/">

            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}

            <input type="submit" name="submit" value="Add Page" />
        </form>
        
        {% else %}
            The specified category does not exist!
        {% endif%}
        
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html>
    <head lang = "en">
        <meta charset = "UTF-8" />
		<title>
			Rango -
			{% block title_block %} 
			    How to Tango with Django!
			{% endblock %}
		</title>
    </head>
    <body>
        <div>
            {% block sidebar_block %}
                {% get_category_list %}
            {% endblock %}
        </div>
        <div>
            {% block body_block %}
                This is body_block's default content.
            {% endblock %}
        </div>
        <hr />
        <div>
            <ul>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
                    <li><a href="{% url 'rango:logout' %}">Logout</a></li>
                    <li><a href="{% url 'rango:add_category' %}">Add New category</a></li>
                {% else %}
                    <li><a href="{% url 'rango:login' %}">login</a></li>
                    <li><a href="{% url 'rango:register' %}">Sign Up</a></li>
                {% endif %}
                <li><a href="{% url 'rango:about' %}">About</a></li>
                <li><a href="{% url 'rango:index' %}">index</a></li>
            </ul>
        </div>
    </body>
</html>

templates/rango/categories.html
<ul>
    {% if categories %}
        {% for c in categories %}
            {% if c == current_category %}
                <li>
                <strong>
                    <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
                </strong>
                </li>
            {% else %}
                <li>
                    <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
                </li>
            {% endif %}
        {% endfor %}
    {% else %}   
        <li><strong>There are no categories present.</strong></li>
    {% endif %}
</ul>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}


{% block body_block %}
    {% if category %}
        <h1>{{ category.name }}</h1>>
        {% if pages %}
            <ul>
            {% for page in pages %}
                <li><a href="{{page.url}}">{{page.title}}</a></li>>
            {% endfor %}
            </ul>>
        {% else %}
            <strong>No pages currently in category.</strong>>
        {% endif %}
        {% if user.is_authenticated %}
            <a href="{% url 'rango:add_page' category.slug %}">Add a Page</a>
        {% endif %}
    {% else %}
        The specified category does not exist!
    {% endif %}
{% endblock %}

templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Homepage
{% endblock %}

{% block body_block %}
        <h1>Rango says...</h1>
        <div>
            {% if user.is_authenticated %}
                howdy {{ user.username }}!
            {% else %}
                hey there partner!
            {% endif %}
        </div>
        <div>
            <div>
                <h2>Most Liked Categories</h2>
            </div>
            {% if categories %}
                <ul>
                    {% for category in categories %}
                        <li>
                            <a href="{% url 'rango:show_category' category.slug %}">{{category.name}}</a>   
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <strong>There are no categories present.</strong>>
            {% endif %}
        </div>


        <div>
            <div>
                <h2>Most Viewed Pages</h2>
            </div>
            {% if pages %}
                <ul>
                    {% for page in pages %}
                        <li><a href="{{ page.url }}">{{ page.title }}</a></li>
                    {% endfor %}
                </ul>
            {% else %}
                <strong>There are no pages present.</strong>
            {% endif %}
        /div>

        <div>
            <img src="{% static 'images/rango.jpg'%}" alt="Picture of Rango"/>
        </div>
{% endblock %}

templates/rango/login.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
<h1>Login to Rango</h1>
<form id='login_form' method='post' action="{% url 'rango:login' %}">
    {% csrf_token %}
    Username:<input type="text" name="username" value="" size="50"/>
    <br/>
    Password:<input type="password" name="password" value="" sieze="50"/>
    <br/>
    <input type="submit" value="submit" />
</form>

{% endblock %}

templates/rango/register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
    <h1>Register for Rango</h1>
    {% if registered %}
        Rango says: <strong>thank you for registering!</strong>
        <a href="{% url 'rango:index' %}">Return to the homepage.</a><br />
    {% else %}
        Rango says: <strong>register here!</strong><br />
        <form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">
        
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}

            <input type="submit" name="submit" value="Register" />
        </form>
    {% endif %}
{% endblock %}

templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Restricted Page
{% endblock %}

{% block body_block %}
    <div>
        Since you're logged in, you can see this text!
    </div>
{% endblock %}